### ISSUE TITLE
[FEAT] 멋사 스터디 1주차 과제

### ISSUE THREAD

**Issue by happine2s** [happine2s/Spring_study#1]
## 📌  Practice

- 웹의 기본 개념 익히기: `서버`와 `클라이언트`의 역할
- 인텔리제이를 사용해 스프링 프로젝트 생성, 스프링과 그레이들 익히기
- 자바 언어의 기초 문법 익히기: `자료형`, `클래스`, `메소드`, `멤버`
- 클래스 정보를 브라우저에 나타내기

## 📝  To-do

- [x] Person 클래스 만들기
- [x] private 멤버변수 3개 이상 만들기(name, age, address, job ...) 
- [x] lombok의 Getter, Setter를 사용
- [x] PersonConroller를 만들고, `http://localhost:8080/myinfo` 에 나의 정보를 나타내기
- [x] Person.java, PersonController.java 를 제출
