### ISSUE TITLE
[FEAT] 멋사 스터디 2주차 과제

### ISSUE THREAD

**Issue by happine2s** [happine2s/Spring_study#3]
## 📌  Practice

- 안쪽에서 바깥쪽으로 나오면서(오른쪽에서 왼쪽으로) 스프링 동작 전체 흐름을 익히기
![FA67DE56-F908-463B-B5EC-C0C41F4B72C9](https://user-images.githubusercontent.com/102134838/191771816-c42565fa-f1d8-4ea5-a15e-5fad8f8fbfa0.png)
- RDBMS: `H2`, `SQL` 사용
- 자바 명령어를 SQL로 번역하고 기본적인 메소드를 제공하는 `JPA`를 공부
- `controller`, `service`, `repository` 계층 개념을 배우고 계층 간 소통을 위한 `DTO`를 사용
- 코드를 절약하는 `lombok`을 사용
- `REST API`: CRUD에 해당하는 GET, POST, PUT, DELETE API를 구축

## 📝  To-do

- [x] `[GET]https://localhost:8080/api/persons/`: 친구 목록 조회
- [x] `[POST]https://localhost:8080/api/persons`: 친구 생성
- [x] `[PUT]https://localhost:8080/api/persons/{id}`: 친구 정보 수정 
- [x] `[DELETE]https://localhost:8080/api/persons/{id}`: 친구 정보 삭제
